name: Deploy Avançado para HostGator

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      with:
        fetch-depth: 2  # Para comparar com commit anterior
        
    - name: Verificar arquivos modificados
      id: changed-files
      uses: tj-actions/changed-files@v40
      with:
        files: |
          **/*.html
          **/*.css
          **/*.js
          **/*.php
          **/*.pdf
          **/*.png
          **/*.jpg
          **/*.jpeg
          **/*.gif
          **/*.svg
          **/*.mp4
          **/*.webm
          .htaccess
          robots.txt
          
    - name: Listar arquivos modificados
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        echo "Arquivos modificados:"
        echo "${{ steps.changed-files.outputs.all_changed_files }}"
        
    - name: Preparar arquivos para deploy
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        # Criar pasta temporária para arquivos de deploy
        mkdir -p deploy-temp
        
        # Copiar apenas arquivos modificados
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          if [ -f "$file" ]; then
            # Criar estrutura de diretórios se necessário
            mkdir -p "deploy-temp/$(dirname "$file")"
            cp "$file" "deploy-temp/$file"
            echo "Preparado: $file"
          fi
        done
        
        # Sempre incluir arquivos essenciais se existirem
        essential_files=(".htaccess" "robots.txt" "index.html")
        for file in "${essential_files[@]}"; do
          if [ -f "$file" ] && [ ! -f "deploy-temp/$file" ]; then
            cp "$file" "deploy-temp/$file"
            echo "Incluído arquivo essencial: $file"
          fi
        done
        
    - name: Deploy arquivos modificados
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: 21
        
        # Usar pasta temporária com apenas arquivos modificados
        local-dir: ./deploy-temp/
        server-dir: /public_html/
        
        # Não limpar arquivos remotos (apenas atualizar modificados)
        dangerous-clean-slate: false
        
        # Log detalhado
        log-level: verbose
        
    - name: Notificar sucesso
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        echo "✅ Deploy concluído com sucesso!"
        echo "Arquivos enviados: ${{ steps.changed-files.outputs.all_changed_files }}"
        
    - name: Sem alterações
      if: steps.changed-files.outputs.any_changed != 'true'
      run: |
        echo "ℹ️ Nenhum arquivo relevante foi modificado. Deploy não necessário."
